import iconUrl from './icon.jpg';
import {questions as fallbackQuestions,summaries,essayLessons,exams,pastEssayThemes,predictedEssayThemes} from './data.js';
import { StatusBar, Style } from '@capacitor/status-bar';

const app=document.querySelector('#app');
const KEY='estudai_state_v8';
const oldKeys=['estudai_state_v5','estudai_state_v6','estudai_state_v7'];
const defaultState={name:'Estudante',avatar:0,xp:0,streak:0,lastStudyDate:null,dailyXp:0,history:[],essayHistory:[],essayDraft:'',theme:predictedEssayThemes[0],tab:'home',seenQuestionIds:[],diagnosticDone:false,difficultyScores:{Linguagens:50,Humanas:50,Natureza:50,Matemática:50},goal:'ENEM 2026',chat:[]};
let state={...defaultState,...JSON.parse(localStorage.getItem(KEY)||'{}')};
if(!localStorage.getItem(KEY)){oldKeys.forEach(k=>localStorage.removeItem(k)); localStorage.setItem(KEY,JSON.stringify(state));}
let quiz=null,diagnostic=null;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=(n,d)=>d?Math.round(n/d*100):0;
const today=()=>new Date().toISOString().slice(0,10);
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const areaMap={Linguagens:'languages',Humanas:'human-sciences',Natureza:'natural-sciences',Matemática:'mathematics'};
const AREAS=['Linguagens','Humanas','Natureza','Matemática'];

function studyActivity(xp){const t=today();if(state.lastStudyDate!==t){if(state.lastStudyDate){const diff=Math.round((new Date(t+'T12:00')-new Date(state.lastStudyDate+'T12:00'))/86400000);state.streak=diff===1?state.streak+1:1}else state.streak=1;state.dailyXp=0;state.lastStudyDate=t}state.xp+=xp;state.dailyXp+=xp;save()}
function setTab(tab){quiz=null;state.tab=tab;save();render();window.scrollTo({top:0,behavior:'smooth'})}
function nav(){return `<nav class="bottomnav">${[['home','⌂','Início'],['desempenho','▥','Desempenho'],['simulados','✎','Simulados'],['redacao','✍','Redação'],['perfil','●','Perfil']].map(([k,i,l])=>`<button data-tab="${k}" class="${state.tab===k?'active':''}"><b>${i}</b><span>${l}</span></button>`).join('')}</nav>`}
function topbar(){return `<header class="topbar"><div class="brand"><img src="${iconUrl}" alt="EstudAI"><strong>EstudAI</strong></div><div class="topstats"><span>🔥 ${state.streak} ${state.streak===1?'dia':'dias'}</span><span>⭐ ${state.xp} XP</span></div></header>`}
function shell(content){return `<div class="shell">${topbar()}<main>${content}</main>${nav()}<button class="prof-fab" data-action="open-prof"><img src="${iconUrl}" alt="Prof. Caramelo"><span>Prof. Caramelo</span></button><div id="profPanel"></div></div>`}
function splash(){return `<div class="splash"><img src="${iconUrl}" alt="EstudAI"><h1>EstudAI</h1><p>Seu caminho inteligente até a aprovação.</p><div class="dots"><i></i><i></i><i></i></div></div>`}

function home(){const weak=AREAS.slice().sort((a,b)=>state.difficultyScores[a]-state.difficultyScores[b]);const daily=Math.min(100,pct(state.dailyXp,60));return `<section class="hero"><span class="eyebrow">${esc(state.goal)}</span><h1>Seu estudo, do seu jeito.</h1><p>O EstudAI dá mais atenção ao que você precisa melhorar sem abandonar as outras áreas.</p><div class="hero-actions"><button class="primary" data-action="personal-study">▶ Estudo personalizado</button><button class="secondary" data-tab="redacao">✍ Treinar redação</button></div><div class="goal"><div><b>Meta de hoje</b><strong>${daily}%</strong></div><div class="progress"><i style="width:${daily}%"></i></div><small>${state.dailyXp}/60 XP hoje</small></div></section><section><div class="title-row"><h2>Foco recomendado</h2><span>baseado no seu desempenho</span></div><div class="focus-grid">${weak.map((a,i)=>`<article class="focus-card tone-${i}"><div class="focus-icon">${['📖','🌎','🧪','📐'][AREAS.indexOf(a)]}</div><div><small>${i===0?'PRIORIDADE':'REVISÃO'}</small><h3>${a}</h3><p>${state.difficultyScores[a]}% de domínio estimado</p></div><button data-action="area-study" data-area="${a}">Praticar →</button></article>`).join('')}</div></section>`}

function desempenho(){const agg={};AREAS.forEach(a=>agg[a]={correct:0,total:0});state.history.forEach(h=>{if(agg[h.area]){agg[h.area].correct+=h.correct;agg[h.area].total+=h.total}else if(h.breakdown)Object.entries(h.breakdown).forEach(([a,v])=>{if(agg[a]){agg[a].correct+=v.correct;agg[a].total+=v.total}})});const total=state.history.reduce((s,h)=>s+h.total,0),correct=state.history.reduce((s,h)=>s+h.correct,0);return `<div class="page-head"><div><span class="eyebrow">DESEMPENHO</span><h1>Sua evolução</h1></div><button class="ghost" data-action="personal-study">Treinar ponto fraco</button></div><div class="metric-grid"><div class="metric-card"><small>Questões feitas</small><strong>${total}</strong></div><div class="metric-card"><small>Aproveitamento</small><strong>${pct(correct,total)}%</strong></div><div class="metric-card"><small>XP total</small><strong>${state.xp}</strong></div><div class="metric-card"><small>Sequência</small><strong>${state.streak}d</strong></div></div><div class="card"><h2>Desempenho por área</h2>${AREAS.map(a=>{const p=agg[a].total?pct(agg[a].correct,agg[a].total):state.difficultyScores[a];return `<div class="area-metric"><div><b>${a}</b><span>${p}%</span></div><div class="progress"><i style="width:${p}%"></i></div><small>${agg[a].total?`${agg[a].correct}/${agg[a].total} acertos`:'estimativa do diagnóstico'}</small></div>`}).join('')}</div><div class="title-row"><h2>Prof. Caramelo recomenda</h2></div><div class="caramelo-tip"><img src="${iconUrl}"><div><b>Seu próximo foco: ${AREAS.slice().sort((a,b)=>state.difficultyScores[a]-state.difficultyScores[b])[0]}</b><p>Vou priorizar questões dessa área nas suas sessões personalizadas e continuar distribuindo as demais matérias.</p></div></div>`}

function simulados(){return `<div class="page-head"><div><span class="eyebrow">SIMULADOS</span><h1>Monte seu treino</h1></div><button class="ghost" data-action="personal-study">⚡ Personalizado</button></div><div class="card simulator"><label>Área</label><div class="segmented" id="areaChoices">${['Todas',...AREAS].map(a=>`<button data-choice-area="${a}" class="${state.simArea===a?'selected':''}">${a}</button>`).join('')}</div><label>Quantidade de questões</label><div class="qty-control"><button data-action="qty-minus">−</button><strong id="qtyValue">${state.simQty||10}</strong><button data-action="qty-plus">+</button></div><small>De 5 a 50 questões. O sistema tenta não repetir questões já vistas.</small><button class="primary full" data-action="generate-quiz">Gerar simulado</button><div class="shortcut-grid"><button data-action="show-reports">📋<b>Relatório Geral</b></button><button data-tab="desempenho">📊<b>Painel de Métricas</b></button><button data-action="show-bank-info">📚<b>Banco de Questões</b></button></div></div><div class="title-row"><h2>Histórico de simulados</h2><span>${state.history.length} salvos</span></div>${state.history.length?`<div class="history-list">${state.history.slice().reverse().map((h,i)=>`<article class="history-card"><div><span class="eyebrow">${esc(h.area)}</span><h3>${h.correct}/${h.total} acertos • ${pct(h.correct,h.total)}%</h3><p>${h.date}${h.year?' • ENEM '+h.year:''}</p></div><div class="history-actions"><button data-action="review-history" data-index="${state.history.length-1-i}">Analisar</button><button data-action="redo-history" data-index="${state.history.length-1-i}">Refazer</button></div></article>`).join('')}</div>`:`<div class="empty">Seus simulados concluídos aparecerão aqui para análise ou para refazer.</div>`}`}
