import {questions,summaries,essayThemes,essayLessons,exams} from './data.js';
const app=document.querySelector('#app');
const KEY='estudai_state_v2';
const defaultState={name:'Estudante',xp:180,streak:3,hearts:5,dailyGoal:60,completed:[],history:[],essays:[],theme:null,tab:'home',onboarded:false};
let state={...defaultState,...JSON.parse(localStorage.getItem(KEY)||'{}')};
let quiz=null;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const setTab=t=>{state.tab=t;save();render()};
const pct=(n,d)=>Math.round((n/d)*100)||0;
function shell(content){return `<div class="shell"><header class="topbar"><div class="topbar-inner"><div class="brand"><div class="brand-mark">🇧🇷</div>EstudAI</div><div class="stat-row"><span class="pill">🔥 ${state.streak} dias</span><span class="pill">⭐ ${state.xp} XP</span><span class="pill">❤️ ${state.hearts}/5</span></div></div></header><div class="layout"><aside class="nav">${navButtons()}</aside><main class="main">${content}</main></div>${bottomNav()}<footer>EstudAI • preparação gamificada para o ENEM</footer></div>`}
function navButtons(){return [['home','🏠 Início'],['trilha','🗺️ Trilha'],['simulados','📝 Simulados'],['provas','📚 Provas ENEM'],['redacao','✍️ Redação'],['resumos','🧠 Resumos'],['progresso','📊 Progresso'],['perfil','👤 Perfil']].map(([k,l])=>`<button data-tab="${k}" class="${state.tab===k?'active':''}">${l}</button>`).join('')}
function bottomNav(){return `<div class="bottomnav">${[['home','🏠','Início'],['trilha','🗺️','Trilha'],['simulados','📝','Quiz'],['redacao','✍️','Redação'],['perfil','👤','Perfil']].map(([k,i,l])=>`<button data-tab="${k}"><b>${i}</b>${l}</button>`).join('')}</div>`}
function home(){const daily=Math.min(100,pct(state.xp%60,60));return `<section class="hero"><div><span class="badge">ENEM 2026</span><h1>Seu caminho inteligente até a aprovação.</h1><p>Estude em trilhas curtas, resolva questões, treine redação e acompanhe sua evolução todos os dias.</p><div class="row"><button class="cta" data-action="quick">Começar missão diária</button><button class="cta secondary" data-tab="redacao">Treinar redação</button></div></div><div class="card"><b>Meta diária</b><div class="metric">${daily}%<small>progresso de hoje</small></div><div class="progress"><div style="width:${daily}%"></div></div><p class="muted">Complete questões e redações para ganhar XP.</p></div></section>
<div class="section-title"><h2>Hoje no EstudAI</h2></div><div class="grid cols3"><div class="card"><h3>🔥 Sequência</h3><div class="metric">${state.streak}<small>dias seguidos</small></div></div><div class="card"><h3>✅ Questões concluídas</h3><div class="metric">${state.completed.length}<small>no total</small></div></div><div class="card"><h3>✍️ Redações</h3><div class="metric">${state.essays.length}<small>treinos salvos</small></div></div></div>
<div class="section-title"><h2>Recomendado para você</h2></div><div class="grid cols2"><div class="card"><h3>Matemática essencial</h3><p class="muted">Porcentagem, razão, estatística e geometria.</p><button class="cta yellow" data-action="area" data-area="Matemática">Praticar agora</button></div><div class="card"><h3>Redação em 15 minutos</h3><p class="muted">Sorteie um tema e escreva apenas tese + proposta de intervenção.</p><button class="cta secondary" data-tab="redacao">Abrir treino</button></div></div>`}
function trail(){const groups=[['Linguagens','📖'],['Humanas','🌎'],['Natureza','🧪'],['Matemática','📐'],['Redação','✍️']];return `<div class="section-title"><h2>Trilha de aprendizagem</h2><span class="muted">estilo missão diária</span></div><div class="trail">${groups.map(([g,ic])=>{const count=state.completed.filter(id=>questions.find(q=>q.id===id)?.area===g).length;return `<div class="lesson ${count>=2?'done':''}"><div class="icon">${ic}</div><div><h3>${g}</h3><p class="muted">${g==='Redação'?'Estrutura, repertório e intervenção':`Treinos focados com questões e explicações.`}</p><div class="progress"><div style="width:${Math.min(100,count*25)}%"></div></div></div><button class="cta" ${g==='Redação'?'data-tab="redacao"':`data-action="area" data-area="${g}"`}>Continuar</button></div>`}).join('')}</div>`}
function simulados(){return `<div class="section-title"><h2>Simulados</h2><span class="muted">gere um treino por área</span></div><div class="card"><div class="grid cols2"><div><label>Área</label><select id="areaSelect" class="field"><option>Todas</option><option>Linguagens</option><option>Humanas</option><option>Natureza</option><option>Matemática</option></select></div><div><label>Quantidade</label><select id="qtySelect" class="field"><option>5</option><option selected>10</option><option>15</option><option>20</option></select></div></div><div class="toolbar"><button class="cta" data-action="generate">Gerar simulado</button></div></div><div class="section-title"><h2>Histórico</h2></div>${state.history.length?`<div class="grid cols3">${state.history.slice().reverse().map(h=>`<div class="card"><span class="badge">${h.area}</span><h3>${h.correct}/${h.total} acertos</h3><p class="muted">${h.date}</p><b>${pct(h.correct,h.total)}% de aproveitamento</b></div>`).join('')}</div>`:`<div class="card muted">Você ainda não concluiu simulados.</div>`}`}
function provas(){return `<div class="section-title"><h2>Provas anteriores do ENEM</h2><span class="muted">2009–2025</span></div><div class="notice">O catálogo abaixo organiza todos os anos. O botão abre a página oficial do INEP com cadernos e gabaritos.</div><div class="exam-grid" style="margin-top:14px">${exams.map(e=>`<div class="exam"><span class="badge">${e.status}</span><strong>${e.year}</strong><p class="muted">Cadernos e gabaritos oficiais</p><a class="cta secondary" href="${e.url}" target="_blank" rel="noopener">Abrir INEP</a></div>`).join('')}</div>`}
function redacao(){const t=state.theme||essayThemes[0];return `<div class="section-title"><h2>Laboratório de Redação</h2><span class="muted">modelo ENEM</span></div><div class="grid cols2"><div class="card"><h3>Tema atual</h3><p style="font-size:20px;font-weight:800">${t}</p><div class="toolbar"><button class="cta yellow" data-action="random-theme">🎲 Sortear tema</button><select id="themeSelect" class="field">${essayThemes.map(x=>`<option ${x===t?'selected':''}>${x}</option>`).join('')}</select></div></div><div class="card"><h3>Checklist rápido</h3><p>✅ tese explícita<br>✅ 2 argumentos desenvolvidos<br>✅ conectivos variados<br>✅ repertório produtivo<br>✅ proposta com agente + ação + meio + finalidade</p></div></div><div class="section-title"><h2>Escreva sua redação</h2></div><div class="card"><textarea id="essayText" placeholder="Comece sua redação aqui..."></textarea><div class="row"><span id="wordCount" class="muted">0 palavras</span><button class="cta" data-action="evaluate">Avaliar treino</button><button class="cta secondary" data-action="save-essay">Salvar rascunho</button></div><div id="essayResult"></div></div><div class="section-title"><h2>Aulas de redação</h2></div><div class="grid cols2">${essayLessons.map(([t,d])=>`<div class="card"><h3>${t}</h3><p class="muted">${d}</p></div>`).join('')}</div>`}
function resumos(){return `<div class="section-title"><h2>Resumos rápidos</h2><span class="muted">revisão de alta frequência</span></div><div class="tabs">${['Todos','Matemática','Natureza','Humanas','Linguagens','Redação'].map(x=>`<button class="tab" data-filter="${x}">${x}</button>`).join('')}</div><div id="summaryGrid" class="grid cols2" style="margin-top:12px">${summaries.map(([a,t,d])=>summaryCard(a,t,d)).join('')}</div>`}
const summaryCard=(a,t,d)=>`<div class="card summary" data-area="${a}"><span class="badge">${a}</span><h3>${t}</h3><p class="muted">${d}</p></div>`;
function progresso(){const done=state.completed.length;const correctHist=state.history.reduce((s,h)=>s+h.correct,0),totalHist=state.history.reduce((s,h)=>s+h.total,0);const p=totalHist?pct(correctHist,totalHist):0;return `<div class="section-title"><h2>Seu progresso</h2></div><div class="grid cols3"><div class="card"><div class="score-ring" style="--p:${p*3.6}deg"><b>${p}%</b></div><p class="muted">Aproveitamento em simulados</p></div><div class="card"><div class="metric">${state.xp}<small>XP total</small></div><hr><div class="metric">${done}<small>questões já praticadas</small></div></div><div class="card"><h3>Conquistas</h3><p>🏅 Primeiro passo ${done>0?'✅':'🔒'}</p><p>🔥 Sequência de 3 dias ${state.streak>=3?'✅':'🔒'}</p><p>✍️ Primeira redação ${state.essays.length?'✅':'🔒'}</p><p>💯 500 XP ${state.xp>=500?'✅':'🔒'}</p></div></div><div class="section-title"><h2>Liga Brasil</h2></div><div class="card">${[['1','Marina',980],['2','João',860],['3',state.name,state.xp],['4','Caio',640],['5','Bia',590]].sort((a,b)=>b[2]-a[2]).map((r,i)=>`<div class="rank"><b>${i+1}º</b><span>${r[1]}</span><b>${r[2]} XP</b></div>`).join('')}</div>`}
function perfil(){return `<div class="section-title"><h2>Perfil</h2></div><div class="card"><div class="row"><div class="avatar">🎓</div><div><h2>${state.name}</h2><p class="muted">Candidato(a) ao ENEM</p></div></div><hr><label>Seu nome</label><input id="nameInput" class="field" value="${state.name}"><div class="toolbar"><button class="cta" data-action="save-profile">Salvar perfil</button><button class="cta secondary" data-action="reset">Resetar progresso</button></div></div>`}
function quizView(){const q=quiz.items[quiz.i],chosen=quiz.answers[quiz.i];return `<div class="section-title"><h2>${quiz.title}</h2><span class="badge">Questão ${quiz.i+1}/${quiz.items.length}</span></div><div class="card"><div class="progress"><div style="width:${pct(quiz.i,quiz.items.length)}%"></div></div><p><span class="badge">${q.area} • ${q.topic}</span></p><div class="question">${q.q}</div><div class="answers">${q.a.map((a,i)=>`<button class="answer ${chosen===i?'selected':''}" data-answer="${i}"><b>${String.fromCharCode(65+i)})</b> ${a}</button>`).join('')}</div><div class="toolbar"><button class="cta" data-action="confirm-answer" ${chosen===undefined?'disabled':''}>Confirmar resposta</button><button class="cta yellow" data-action="eliminate">✨ Facilitar</button></div><div id="feedback"></div></div>`}
function finishQuiz(){const correct=quiz.answers.filter((a,i)=>a===quiz.items[i].c).length;state.xp+=correct*10;state.hearts=Math.max(0,state.hearts-(quiz.items.length-correct));quiz.items.forEach(q=>{if(!state.completed.includes(q.id))state.completed.push(q.id)});state.history.push({area:quiz.area,correct,total:quiz.items.length,date:new Date().toLocaleDateString('pt-BR')});save();const total=quiz.items.length;quiz=null;return `<div class="card" style="text-align:center"><h1>Simulado concluído! 🎉</h1><div class="metric">${correct}/${total}<small>acertos</small></div><h2>${pct(correct,total)}% de aproveitamento</h2><p class="muted">Você ganhou ${correct*10} XP.</p><button class="cta" data-tab="simulados">Ver histórico</button></div>`}
function render(){let content;if(quiz)content=quiz.finished?finishQuiz():quizView();else content=({home,trail,simulados,provas,redacao,resumos,progresso,perfil}[state.tab]||home)();app.innerHTML=shell(content);bind();}
function startQuiz(area='Todas',qty=10){let pool=area==='Todas'?questions:questions.filter(q=>q.area===area);pool=[...pool].sort(()=>Math.random()-.5);while(pool.length<qty)pool=[...pool,...pool];quiz={title:area==='Todas'?'Simulado misto':`Treino de ${area}`,area,items:pool.slice(0,qty),i:0,answers:[],finished:false};render()}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action,b));document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{quiz.answers[quiz.i]=Number(b.dataset.answer);render()});const ta=document.querySelector('#essayText');if(ta)ta.oninput=()=>document.querySelector('#wordCount').textContent=`${ta.value.trim()?ta.value.trim().split(/\s+/).length:0} palavras`;const ts=document.querySelector('#themeSelect');if(ts)ts.onchange=()=>{state.theme=ts.value;save();render()};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{const f=b.dataset.filter;document.querySelectorAll('.summary').forEach(c=>c.style.display=(f==='Todos'||c.dataset.area===f)?'block':'none')});}
function action(a,b){if(a==='quick')startQuiz('Todas',5);if(a==='area')startQuiz(b.dataset.area,5);if(a==='generate')startQuiz(document.querySelector('#areaSelect').value,Number(document.querySelector('#qtySelect').value));if(a==='confirm-answer'){const q=quiz.items[quiz.i],ans=quiz.answers[quiz.i],fb=document.querySelector('#feedback');fb.innerHTML=`<div class="notice ${ans===q.c?'success':'danger'}" style="margin-top:14px"><b>${ans===q.c?'Resposta correta! ✅':'Resposta incorreta ❌'}</b><p>${q.e}</p><button class="cta" id="nextQ">${quiz.i===quiz.items.length-1?'Ver resultado':'Próxima questão'}</button></div>`;document.querySelector('#nextQ').onclick=()=>{quiz.i++;if(quiz.i>=quiz.items.length)quiz.finished=true;render()}}if(a==='eliminate'){const q=quiz.items[quiz.i];const wrong=q.a.map((_,i)=>i).filter(i=>i!==q.c).slice(0,2);document.querySelectorAll('[data-answer]').forEach(x=>{if(wrong.includes(Number(x.dataset.answer)))x.style.opacity=.28})}if(a==='random-theme'){state.theme=essayThemes[Math.floor(Math.random()*essayThemes.length)];save();render()}if(a==='save-essay'){const text=document.querySelector('#essayText').value;state.essays.push({theme:state.theme||essayThemes[0],text,date:new Date().toLocaleDateString('pt-BR')});state.xp+=20;save();alert('Rascunho salvo! +20 XP')}if(a==='evaluate'){const text=document.querySelector('#essayText').value.trim();const words=text?text.split(/\s+/).length:0;const paragraphs=text.split(/\n\s*\n/).filter(Boolean).length;const connectors=(text.match(/portanto|além disso|entretanto|assim|desse modo|porém|logo|consequentemente/gi)||[]).length;const proposal=/governo|estado|escola|ministério|sociedade|empresa|mídia/i.test(text)&&/deve|deverá|precisa|promover|criar|implementar|ampliar/i.test(text);let s1=Math.min(200,80+Math.floor(words/2));let s2=Math.min(200,80+paragraphs*25);let s3=Math.min(200,80+Math.min(4,connectors)*30);let s4=Math.min(200,100+Math.min(5,connectors)*20);let s5=proposal?180:100;const total=s1+s2+s3+s4+s5;document.querySelector('#essayResult').innerHTML=`<div class="notice success" style="margin-top:14px"><h3>Avaliação de treino: ${total}/1000</h3><p>C1 ${s1} • C2 ${s2} • C3 ${s3} • C4 ${s4} • C5 ${s5}</p><p class="muted">Esta é uma estimativa local baseada em estrutura e sinais textuais; não substitui correção humana ou um modelo de IA especializado.</p></div>`}if(a==='save-profile'){state.name=document.querySelector('#nameInput').value.trim()||'Estudante';save();render()}if(a==='reset'){if(confirm('Tem certeza?')){localStorage.removeItem(KEY);state={...defaultState};render()}}}
render();
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
