import iconUrl from './icon.jpg';
import avatarsUrl from './avatars_hd.jpg';
import mascotUrl from './prof-caramelo.jpg';
import {questions as fallbackQuestions,summaries,essayLessons,exams,pastEssayThemes,predictedEssayThemes} from './data.js';
import { StatusBar, Style } from '@capacitor/status-bar';

const app=document.querySelector('#app');
const KEY='estudai_state_v8';
const oldKeys=['estudai_state_v5','estudai_state_v6','estudai_state_v7'];
const defaultState={name:'Estudante',avatar:0,xp:0,streak:0,lastStudyDate:null,dailyXp:0,history:[],essayHistory:[],essayDraft:'',theme:predictedEssayThemes[0],tab:'home',seenQuestionIds:[],questionCache:[],diagnosticDone:false,selfReportedWeak:null,difficultyScores:{Linguagens:50,Humanas:50,Natureza:50,Matemática:50},goal:'ENEM 2026',chat:[],simAreas:['Todas'],simQty:10};
let state={...defaultState,...JSON.parse(localStorage.getItem(KEY)||'{}')};
state.simAreas=Array.isArray(state.simAreas)&&state.simAreas.length?state.simAreas:(state.simArea&&state.simArea!=='Todas'?[state.simArea]:['Todas']);
state.questionCache=Array.isArray(state.questionCache)?state.questionCache:[];
state.chat=Array.isArray(state.chat)?state.chat:[];
if(!localStorage.getItem(KEY)){oldKeys.forEach(k=>localStorage.removeItem(k)); localStorage.setItem(KEY,JSON.stringify(state));}
let quiz=null,diagnostic=null;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=(n,d)=>d?Math.round(n/d*100):0;
const today=()=>new Date().toISOString().slice(0,10);
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const areaMap={Linguagens:'languages',Humanas:'human-sciences',Natureza:'natural-sciences',Matemática:'mathematics'};
const AREAS=['Linguagens','Humanas','Natureza','Matemática'];

function studyActivity(xp){const t=today();if(state.lastStudyDate!==t){if(state.lastStudyDate){const diff=Math.round((new Date(t+'T12:00')-new Date(state.lastStudyDate+'T12:00'))/86400000);state.streak=diff===1?state.streak+1:1}else state.streak=1;state.dailyXp=0;state.lastStudyDate=t}state.xp+=xp;state.dailyXp+=xp;save()}
function setTab(tab){quiz=null;state.tab=tab;save();render();window.scrollTo({top:0,behavior:'smooth'})}
function nav(){return `<nav class="bottomnav">${[['home','⌂','Início'],['desempenho','▥','Desempenho'],['simulados','✎','Simulados'],['redacao','✍','Redação'],['perfil','●','Perfil']].map(([k,i,l])=>`<button data-tab="${k}" class="${state.tab===k?'active':''}"><b>${i}</b><span>${l}</span></button>`).join('')}</nav>`}
function topbar(){return `<header class="topbar"><div class="brand"><img src="${iconUrl}" alt="EstudAI"><strong>EstudAI</strong></div><div class="topstats"><span>🔥 ${state.streak} ${state.streak===1?'dia':'dias'}</span><span>⭐ ${state.xp} XP</span></div></header>`}
function shell(content){return `<div class="shell">${topbar()}<main>${content}</main>${nav()}<button class="prof-fab" data-action="open-prof" aria-label="Abrir Prof. Caramelo"><img src="${mascotUrl}" alt="Prof. Caramelo"><span>Prof. Caramelo</span></button><div id="profPanel"></div></div>`}
function splash(){return `<div class="splash"><img src="${iconUrl}" alt="EstudAI"><h1>EstudAI</h1><p>Seu caminho inteligente até a aprovação.</p><div class="dots"><i></i><i></i><i></i></div></div>`}

function home(){const weak=AREAS.slice().sort((a,b)=>state.difficultyScores[a]-state.difficultyScores[b]);const daily=Math.min(100,pct(state.dailyXp,60));return `<section class="hero"><span class="eyebrow">${esc(state.goal)}</span><h1>Seu estudo, do seu jeito.</h1><p>O EstudAI dá mais atenção ao que você precisa melhorar sem abandonar as outras áreas.</p><div class="hero-actions"><button class="primary" data-action="personal-study">▶ Estudo personalizado</button><button class="secondary" data-tab="redacao">✍ Treinar redação</button></div><div class="goal"><div><b>Meta de hoje</b><strong>${daily}%</strong></div><div class="progress"><i style="width:${daily}%"></i></div><small>${state.dailyXp}/60 XP hoje</small></div></section><section><div class="title-row"><h2>Foco recomendado</h2><span>baseado no seu desempenho</span></div><div class="focus-grid">${weak.map((a,i)=>`<article class="focus-card tone-${i}"><div class="focus-icon">${['📖','🌎','🧪','📐'][AREAS.indexOf(a)]}</div><div><small>${i===0?'PRIORIDADE':'REVISÃO'}</small><h3>${a}</h3><p>${state.difficultyScores[a]}% de domínio estimado</p></div><button data-action="area-study" data-area="${a}">Praticar →</button></article>`).join('')}</div></section>`}

function desempenho(){const agg={};AREAS.forEach(a=>agg[a]={correct:0,total:0});state.history.forEach(h=>{if(h.breakdown)Object.entries(h.breakdown).forEach(([a,v])=>{if(agg[a]){agg[a].correct+=v.correct;agg[a].total+=v.total}});else if(agg[h.area]){agg[h.area].correct+=h.correct;agg[h.area].total+=h.total}});const total=state.history.reduce((s,h)=>s+h.total,0),correct=state.history.reduce((s,h)=>s+h.correct,0),accuracy=pct(correct,total);const weak=state.selfReportedWeak||AREAS.slice().sort((a,b)=>state.difficultyScores[a]-state.difficultyScores[b])[0];const recent=state.history.slice(-6);return `<section class="metrics-hero"><span class="eyebrow">📊 PAINEL DE MÉTRICAS</span><h1>Sua evolução</h1><div class="streak-banner"><img src="${mascotUrl}"><div><small>SEQUÊNCIA DE ESTUDO</small><b>${state.streak} ${state.streak===1?'dia seguido':'dias seguidos'}</b></div></div></section><div class="dashboard-grid"><article class="dash-card pink"><span>📝</span><small>QUESTÕES RESPONDIDAS</small><strong>${total}</strong></article><article class="dash-card yellow-card"><span>🎯</span><small>TAXA DE ACERTO GERAL</small><strong>${accuracy}%</strong></article><article class="dash-card blue-card"><span>📋</span><small>SIMULADOS REALIZADOS</small><strong>${state.history.length}</strong></article><article class="dash-card purple-card"><span>🔥</span><small>SEQUÊNCIA DE ESTUDO</small><strong>${state.streak}d</strong></article><article class="dash-card pink"><span>⭐</span><small>XP TOTAL</small><strong>${state.xp}</strong></article></div><section class="metric-section"><h2>📈 Evolução do desempenho</h2><div class="evolution-chart">${recent.length?recent.map((h,i)=>{const p=pct(h.correct,h.total);return `<div class="evo-col"><b>${p}%</b><i style="height:${Math.max(12,p)}%"></i><small>${h.date.slice(0,5)}</small></div>`}).join(''):'<p class="muted">Conclua simulados para acompanhar sua evolução.</p>'}</div></section><section class="metric-section"><h2>📚 Desempenho por área</h2>${AREAS.map(a=>{const p=agg[a].total?pct(agg[a].correct,agg[a].total):state.difficultyScores[a];return `<div class="area-metric"><div><b>${a}</b><span>${p}%</span></div><div class="progress"><i style="width:${p}%"></i></div><small>${agg[a].total?`${agg[a].correct}/${agg[a].total} acertos`:'estimativa do diagnóstico'}</small></div>`}).join('')}</section><section class="priority-card"><h2>🎯 Tópicos prioritários para revisão</h2><p>O Prof. Caramelo vai dar atenção extra a <b>${weak}</b>, sem deixar as demais áreas de lado. 🐾</p><button class="primary" data-action="personal-study">Treinar meu ponto fraco ✨</button></section>`}

function simulados(){const selected=state.simAreas||['Todas'];return `<div class="page-head sim-page-head"><div><span class="eyebrow">SIMULADOS</span><h1>Monte seu treino</h1></div><button class="ghost" data-action="personal-study">⚡ Personalizado • 10</button></div><div class="card simulator"><label>Áreas <small>escolha quantas quiser</small></label><div class="segmented multi" id="areaChoices">${['Todas',...AREAS].map(a=>`<button data-choice-area="${a}" class="${selected.includes(a)?'selected':''}">${a}</button>`).join('')}</div><label>Quantidade de questões</label><div class="qty-control"><button data-action="qty-minus">−</button><strong id="qtyValue">${state.simQty||10}</strong><button data-action="qty-plus">+</button></div><small>De 5 a 50 questões. Novas questões são priorizadas e as tentativas antigas ficam salvas no histórico.</small><button class="primary full" data-action="generate-quiz">Gerar simulado ✨</button><div class="shortcut-grid"><button data-action="show-reports">📋<b>Relatório Geral</b></button><button data-tab="desempenho">📊<b>Painel de Métricas</b></button><button data-action="show-bank-info">📚<b>Banco de Questões</b></button></div></div><div class="title-row"><h2>Histórico de simulados</h2><span>${state.history.length} salvos</span></div>${state.history.length?`<div class="history-list">${state.history.slice().reverse().map((h,i)=>`<article class="history-card"><div><span class="eyebrow">${esc(h.area)}</span><h3>${h.correct}/${h.total} acertos • ${pct(h.correct,h.total)}%</h3><p>${h.date}${h.year?' • ENEM '+h.year:''}</p></div><div class="history-actions"><button data-action="review-history" data-index="${state.history